### ISSUE TITLE
Client to work on Windows

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/git-watch#20]
So people could test it out.

**Comment by ScalaWilliam** [comment]
```
git-watch --push-execute='echo hi && echo "%sha%" && dir'
```

Breaks.

**Comment by ScalaWilliam** [comment]
Fixed by 35e293ce0da2156ff7d732003ee5577af131053d - a Windows problem rather than anything else.

**Comment by ScalaWilliam** [comment]
Big thanks to @livelybug for finding the problem :)

**Comment by livelybug** [comment]
@ScalaWilliam learned a lot from you, thank you
